// Bun.ant.CellSegmenter (claude-code 2.1.274+) is a native terminal cell segmenter the
// ink renderer requires at startup. The contract, taken from the renderer chunk:
//
//   new CellSegmenter({ ambiguousIsNarrow, substitute, screen })
//     substitute: [[from, to], ...] code point ranges rendered as U+FFFD
//     screen: { widthMask, narrow, wide, spacerTail, spacerHead, emptyCharIndex,
//               spacerCharIndex, emptyWord, tabWidth }
//   .graphemes / .sgrKeys / .sgrCloseKeys / .uris  — growing string tables the caller
//     reads by index (index 0 of the key tables is the "no style" run)
//   .segment(text, cells, runs, reorder) -> count | -needed
//     cells[2i]   = grapheme table index
//     cells[2i+1] = width (bits 0..7) | tab flag (bit 8) | run index << 10
//     runs[2r]    = sgrKeys index, runs[2r+1] = uris index; run indices must not
//                   decrease along the text (the caller sizes its run table from
//                   the last cell's run index unless reorder is set)
//     a negative return means the buffers hold fewer than -return entries
//   .paint(screenCells, screenWidth, x, y, cells, count, unused, charIndices, runWords)
//     writes the segmented cells at row y from column x into the screen's packed
//     Int32 pairs (char pool index, word) where word = runWords[run] | width bits
//     for narrow/wide, and spacer cells follow every wide cell; returns
//     endX + firstX * 2^20 + endX * 2^36 so the caller recovers damage bounds
//   .setCell(screenCells, screenWidth, x, y, charIndex, word) -> same encoding
//
// This is a JavaScript port; the renderer only reads what the arrays and the
// return values carry, so fidelity is in those layouts, not in performance.
export const CELL_SEGMENTER_SHIM = [
  "class __cccCellSegmenter {",
  "  constructor(options) {",
  "    this.screen = options.screen;",
  "    this.ambiguousIsNarrow = options.ambiguousIsNarrow !== false;",
  "    this.substitute = (options.substitute ?? []).map(([from, to]) => [from, to ?? from]);",
  '    this.graphemes = [""];',
  '    this.sgrKeys = [""];',
  '    this.sgrCloseKeys = [""];',
  '    this.uris = [""];',
  "    this.graphemeIds = new Map([['', 0]]);",
  '    this.segmenter = typeof Intl.Segmenter === "function" ? new Intl.Segmenter(undefined, { granularity: "grapheme" }) : null;',
  "  }",
  "  internGrapheme(text) {",
  "    let id = this.graphemeIds.get(text);",
  "    if (id === undefined) { id = this.graphemes.length; this.graphemes.push(text); this.graphemeIds.set(text, id); }",
  "    return id;",
  "  }",
  "  internString(table, value) {",
  "    const index = table.indexOf(value);",
  "    if (index !== -1) return index;",
  "    table.push(value);",
  "    return table.length - 1;",
  "  }",
  "  substituted(grapheme) {",
  "    const code = grapheme.codePointAt(0) ?? 0;",
  "    for (const [from, to] of this.substitute) if (code >= from && code <= to) return true;",
  "    return false;",
  "  }",
  "  *graphemesOf(text) {",
  "    if (this.segmenter) { for (const part of this.segmenter.segment(text)) yield part.segment; return; }",
  "    for (const char of text) yield char;",
  "  }",
  "  // splits text into escape sequences and visible graphemes, tracking the open SGR",
  "  // codes and OSC 8 hyperlink so every visible grapheme lands in a run",
  "  segment(text, cells, runs, reorder) {",
  "    const source = String(text ?? '');",
  "    const escapeRe = /\\x1B(?:\\[[0-?]*[ -/]*[@-~]|\\][^\\x07\\x1B]*(?:\\x07|\\x1B\\\\)|[@-Z\\\\-_])/y;",
  "    const sgrRe = /^\\x1B\\[([0-9;]*)m$/;",
  "    const oscRe = /^\\x1B\\]8;[^;]*;([^\\x07\\x1B]*)(?:\\x07|\\x1B\\\\)$/;",
  "    let opens = [];",
  '    let uri = "";',
  "    let runIndex = 0;",
  "    let runKey = '0:0';",
  "    let count = 0;",
  "    let runCount = 1;",
  "    const capacity = Math.floor(Math.min(cells.length, runs.length) / 2);",
  "    if (runs.length >= 2) { runs[0] = 0; runs[1] = 0; }",
  "    const resolveRun = () => {",
  "      const key = opens.map((open) => open.code).join('\\0');",
  "      const sgr = key === '' ? 0 : this.internString(this.sgrKeys, key);",
  "      if (sgr !== 0 && this.sgrCloseKeys.length <= sgr) this.sgrCloseKeys[sgr] = opens.map((open) => open.endCode).join('\\0');",
  "      const link = uri === '' ? 0 : this.internString(this.uris, uri);",
  "      const nextKey = sgr + ':' + link;",
  "      if (nextKey === runKey) return;",
  "      runKey = nextKey;",
  "      runIndex = runCount++;",
  "      if (2 * runIndex + 1 < runs.length) { runs[2 * runIndex] = sgr; runs[2 * runIndex + 1] = link; }",
  "    };",
  "    let position = 0;",
  "    const pending = [];",
  "    while (position < source.length) {",
  "      escapeRe.lastIndex = position;",
  "      const escape = escapeRe.exec(source);",
  "      if (escape) {",
  "        const sequence = escape[0];",
  "        position += sequence.length;",
  "        const sgr = sgrRe.exec(sequence);",
  "        if (sgr) {",
  "          for (const code of __cccSplitSgr(sgr[1])) opens = __cccApplySgr(opens, code);",
  "          resolveRun();",
  "          continue;",
  "        }",
  "        const osc = oscRe.exec(sequence);",
  "        if (osc) { uri = osc[1]; resolveRun(); }",
  "        continue;",
  "      }",
  "      const rest = source.slice(position);",
  "      let grapheme = rest;",
  "      for (const part of this.graphemesOf(rest)) { grapheme = part; break; }",
  "      position += grapheme.length;",
  "      let width;",
  "      let flags = 0;",
  "      if (grapheme === '\\t') { width = 0; flags = 256; }",
  "      else if (this.substituted(grapheme)) { grapheme = '\\uFFFD'; width = 1; }",
  "      else { width = __cccStringWidth(grapheme); if (width > 2) width = 2; }",
  "      const code = grapheme.codePointAt(0) ?? 0;",
  "      if (width === 0 && flags === 0 && (code < 32 || (code >= 127 && code < 160))) continue;",
  "      pending.push(this.internGrapheme(grapheme), width | flags | (runIndex << 10));",
  "      count++;",
  "    }",
  "    if (Math.max(count, runCount) > capacity) return -Math.max(count, runCount);",
  "    for (let i = 0; i < pending.length; i++) cells[i] = pending[i];",
  "    return count;",
  "  }",
  "  paint(screenCells, screenWidth, x, y, cells, count, _unused, charIndices, runWords) {",
  "    const screen = this.screen;",
  "    let column = x;",
  "    const rowBase = y * screenWidth;",
  "    let first = -1;",
  "    for (let i = 0; i < count; i++) {",
  "      const packed = cells[2 * i + 1];",
  "      const run = packed >>> 10;",
  "      const styleWord = runWords[run] ?? screen.emptyWord;",
  "      let width = packed & 255;",
  "      if ((packed & 256) !== 0) width = screen.tabWidth - (column % screen.tabWidth);",
  "      if ((packed & 256) !== 0) {",
  "        for (let k = 0; k < width && column < screenWidth; k++, column++) {",
  "          if (first === -1) first = column;",
  "          const index = (rowBase + column) << 1;",
  "          screenCells[index] = screen.emptyCharIndex;",
  "          screenCells[index + 1] = (styleWord & ~screen.widthMask) | screen.narrow;",
  "        }",
  "        continue;",
  "      }",
  "      if (width === 0) {",
  "        // a zero-width grapheme joins the previous cell; keep it as its own narrow cell",
  "        // when nothing precedes it so the text is not lost",
  "        if (column > x) continue;",
  "        width = 1;",
  "      }",
  "      if (column >= screenWidth) break;",
  "      if (width === 2 && column + 1 >= screenWidth) {",
  "        const index = (rowBase + column) << 1;",
  "        if (first === -1) first = column;",
  "        screenCells[index] = screen.emptyCharIndex;",
  "        screenCells[index + 1] = (styleWord & ~screen.widthMask) | screen.narrow;",
  "        column++;",
  "        break;",
  "      }",
  "      if (first === -1) first = column;",
  "      const index = (rowBase + column) << 1;",
  "      screenCells[index] = charIndices[cells[2 * i]];",
  "      screenCells[index + 1] = (styleWord & ~screen.widthMask) | (width === 2 ? screen.wide : screen.narrow);",
  "      column++;",
  "      if (width === 2) {",
  "        const tail = (rowBase + column) << 1;",
  "        screenCells[tail] = screen.spacerCharIndex;",
  "        screenCells[tail + 1] = (styleWord & ~screen.widthMask) | screen.spacerTail;",
  "        column++;",
  "      }",
  "    }",
  "    if (first === -1) first = x;",
  "    return column + first * 1048576 + column * 68719476736;",
  "  }",
  "  setCell(screenCells, screenWidth, x, y, charIndex, word) {",
  "    const screen = this.screen;",
  "    const index = (y * screenWidth + x) << 1;",
  "    screenCells[index] = charIndex;",
  "    screenCells[index + 1] = word;",
  "    let end = x + 1;",
  "    if ((word & screen.widthMask) === screen.wide && x + 1 < screenWidth) {",
  "      screenCells[index + 2] = screen.spacerCharIndex;",
  "      screenCells[index + 3] = (word & ~screen.widthMask) | screen.spacerTail;",
  "      end = x + 2;",
  "    }",
  "    return end + x * 1048576 + end * 68719476736;",
  "  }",
  "}",
  "// one parameter group per code, keeping 38;5;n / 38;2;r;g;b together, so every",
  "// stored key matches the renderer's single-code SGR pattern",
  "function __cccSplitSgr(params) {",
  "  if (params === '') return ['0'];",
  "  const parts = params.split(';');",
  "  const codes = [];",
  "  for (let i = 0; i < parts.length; i++) {",
  "    const part = parts[i];",
  "    if ((part === '38' || part === '48' || part === '58') && parts[i + 1] === '5') { codes.push(parts.slice(i, i + 3).join(';')); i += 2; }",
  "    else if ((part === '38' || part === '48' || part === '58') && parts[i + 1] === '2') { codes.push(parts.slice(i, i + 5).join(';')); i += 4; }",
  "    else codes.push(part === '' ? '0' : part);",
  "  }",
  "  return codes;",
  "}",
  "const __cccSgrCloseByOpen = new Map([[1, 22], [2, 22], [3, 23], [4, 24], [5, 25], [6, 25], [7, 27], [8, 28], [9, 29], [21, 24], [53, 55]]);",
  "const __cccSgrCloseCodes = new Set([0, 22, 23, 24, 25, 27, 28, 29, 39, 49, 55]);",
  "function __cccSgrEndCode(first) {",
  "  if ((first >= 30 && first <= 38) || (first >= 90 && first <= 97)) return '\\x1B[39m';",
  "  if ((first >= 40 && first <= 48) || (first >= 100 && first <= 107)) return '\\x1B[49m';",
  "  const close = __cccSgrCloseByOpen.get(first);",
  "  return close === undefined ? '\\x1B[0m' : '\\x1B[' + close + 'm';",
  "}",
  "// mirrors the renderer's style folding: reset clears, a close code drops what it",
  "// closes, bold and dim coexist, anything else replaces the entry it would close",
  "function __cccApplySgr(opens, code) {",
  "  const first = Number.parseInt(code, 10);",
  "  if (first === 0) return [];",
  "  const sequence = '\\x1B[' + code + 'm';",
  "  if (__cccSgrCloseCodes.has(first)) return opens.filter((open) => open.endCode !== sequence);",
  "  const endCode = __cccSgrEndCode(first);",
  "  if (first === 1 || first === 2) {",
  "    if (opens.some((open) => open.code === sequence)) return opens;",
  "    return [...opens, { code: sequence, endCode }];",
  "  }",
  "  return [...opens.filter((open) => open.endCode !== endCode), { code: sequence, endCode }];",
  "}",
  "__cccBun.ant.CellSegmenter = __cccCellSegmenter;",
].join("\n");
