import { createHash } from "crypto";
import { NATIVE_BUN_ENTRY_MARKER } from "./constants";

const PREAMBLE = [
  'import { createRequire } from "module";',
  'import { fileURLToPath } from "url";',
  'import { dirname } from "path";',
  "",
  "// node-populated when running as ESM; __filename/__dirname fall back in case the bundle wrapper is invoked as CJS.",
  'const __filename__ = typeof __filename !== "undefined" ? __filename : fileURLToPath(import.meta.url);',
  'const __dirname__ = typeof __dirname !== "undefined" ? __dirname : dirname(__filename__);',
  "",
  "// The cached cli.mjs lives under ~/.cache/ccc/... which has NO node_modules chain to the",
  "// launcher's deps (yaml, undici, ajv, etc.). Anchor require() on the wrapper's",
  "// package.json so fallback paths find their modules.",
  "const __requireAnchor = process.env.CCC_CLAUDE_WRAPPER_PKG_JSON || import.meta.url;",
  "const __baseRequire = createRequire(__requireAnchor);",
  "",
  "// bun ships node-fetch + ws as builtins; node does not. shim at require-time only.",
  "function __require(specifier) {",
  '  if (specifier === "node-fetch") {',
  "    const fetchFn = globalThis.fetch;",
  '    if (typeof fetchFn !== "function") {',
  '      throw new Error("node-fetch shim: global fetch is not available; upgrade to node 18+ or install node-fetch");',
  "    }",
  "    return Object.assign(fetchFn, {",
  "      default: fetchFn,",
  "      Headers: globalThis.Headers,",
  "      Request: globalThis.Request,",
  "      Response: globalThis.Response,",
  "      FormData: globalThis.FormData,",
  "      Blob: globalThis.Blob,",
  "      File: globalThis.File,",
  "    });",
  "  }",
  '  if (specifier === "ws") {',
  '    try { return __baseRequire("ws"); } catch {}',
  "    const WSImpl = globalThis.WebSocket;",
  '    if (typeof WSImpl === "function") {',
  "      WSImpl.CONNECTING ??= 0;",
  "      WSImpl.OPEN ??= 1;",
  "      WSImpl.CLOSING ??= 2;",
  "      WSImpl.CLOSED ??= 3;",
  "      return WSImpl;",
  "    }",
  '    const { EventEmitter } = __baseRequire("events");',
  "    class StubWebSocket extends EventEmitter {",
  "      static CONNECTING = 0;",
  "      static OPEN = 1;",
  "      static CLOSING = 2;",
  "      static CLOSED = 3;",
  "      readyState = StubWebSocket.CONNECTING;",
  "      constructor(url) {",
  "        super();",
  "        this.url = url;",
  '        queueMicrotask(() => { this.readyState = StubWebSocket.OPEN; this.emit("open"); });',
  "      }",
  "      send() {}",
  "      ping() {}",
  '      close() { if (this.readyState !== StubWebSocket.CLOSED) { this.readyState = StubWebSocket.CLOSED; this.emit("close"); } }',
  "      terminate() { this.close(); }",
  "    }",
  "    return StubWebSocket;",
  "  }",
  "  // bun compiles some native assets (e.g. ripgrep.node) into the binary and references",
  "  // them via /$bunfs/root/... specifiers. we cannot load these from the extracted JS;",
  "  // CCC sets USE_BUILTIN_RIPGREP=0 so claude-code falls back to system ripgrep. if a",
  "  // future bundle tries to require a new bunfs asset, surface a clear error rather than",
  "  // a confusing MODULE_NOT_FOUND.",
  '  if (typeof specifier === "string" && specifier.startsWith("/$bunfs/root/")) {',
  "    throw new Error(",
  '      "native-preamble: unexpected bunfs asset require: " + specifier + ". " +',
  '      "The extracted bundle cannot load bun-embedded native assets. " +',
  '      "If this is a new asset type, extend __require in src/native/preamble.ts."',
  "    );",
  "  }",
  "  return __baseRequire(specifier);",
  "}",
  "",
  "function __cccRequireDefault(specifier) {",
  "  try {",
  "    const mod = __baseRequire(specifier);",
  "    return mod?.default ?? mod;",
  "  } catch {",
  "    return null;",
  "  }",
  "}",
  'const __cccStringWidthPackage = __cccRequireDefault("string-width");',
  'const __cccStripAnsiPackage = __cccRequireDefault("strip-ansi");',
  'const __cccWrapAnsiPackage = __cccRequireDefault("wrap-ansi");',
  "function __cccStringWidth(value) {",
  '  if (typeof __cccStringWidthPackage === "function") return __cccStringWidthPackage(String(value));',
  "  let width = 0;",
  "  for (const char of String(value)) {",
  "    const code = char.codePointAt(0) ?? 0;",
  "    if (code === 0 || code < 32 || (code >= 127 && code < 160)) continue;",
  "    width += code >= 4352 && code <= 4447 || code >= 9001 && code <= 9002 || code >= 11904 && code <= 42191 || code >= 44032 && code <= 55203 || code >= 63744 && code <= 64255 || code >= 65040 && code <= 65049 || code >= 65072 && code <= 65131 || code >= 65281 && code <= 65376 || code >= 65504 && code <= 65510 || code >= 127744 && code <= 129791 || code >= 131072 && code <= 196607 ? 2 : 1;",
  "  }",
  "  return width;",
  "}",
  "function __cccBunHash(value, seed) {",
  '  const hash = __baseRequire("crypto").createHash("sha256");',
  "  if (seed !== undefined) hash.update(String(seed));",
  '  hash.update(typeof value === "string" ? value : String(value));',
  '  return Number.parseInt(hash.digest("hex").slice(0, 13), 16);',
  "}",
  "function __cccToBuffer(data) {",
  "  if (Buffer.isBuffer(data)) return data;",
  "  if (data instanceof Uint8Array) return Buffer.from(data);",
  "  return Buffer.from(String(data));",
  "}",
  "function __cccStripAnsi(value) {",
  '  if (typeof __cccStripAnsiPackage === "function") return __cccStripAnsiPackage(String(value));',
  '  return String(value).replace(/\\x1B(?:[@-Z\\\\-_]|\\[[0-?]*[ -/]*[@-~]|\\][^\\x07]*(?:\\x07|\\x1B\\\\))/g, "");',
  "}",
  "function __cccWrapAnsi(value, columns, options) {",
  "  const text = String(value);",
  "  if (!Number.isFinite(columns) || columns <= 0) return text;",
  '  if (typeof __cccWrapAnsiPackage === "function") return __cccWrapAnsiPackage(text, columns, options);',
  "  const lines = [];",
  '  for (const line of text.split("\\n")) {',
  '    let current = "";',
  "    let width = 0;",
  "    for (const char of line) {",
  "      const charWidth = __cccStringWidth(char);",
  "      if (width > 0 && width + charWidth > columns) {",
  "        lines.push(current);",
  "        current = char;",
  "        width = charWidth;",
  "      } else {",
  "        current += char;",
  "        width += charWidth;",
  "      }",
  "    }",
  "    lines.push(current);",
  "  }",
  '  return lines.join("\\n");',
  "}",
  "function __cccParseVersion(version) {",
  "  const match = String(version).trim().match(/^(\\d+)(?:\\.(\\d+))?(?:\\.(\\d+))?(?:[-+].*)?$/);",
  "  return match ? [Number(match[1] ?? 0), Number(match[2] ?? 0), Number(match[3] ?? 0)] : [0, 0, 0];",
  "}",
  "function __cccCompareVersions(left, right) {",
  "  const a = __cccParseVersion(left);",
  "  const b = __cccParseVersion(right);",
  "  for (let i = 0; i < 3; i++) if (a[i] !== b[i]) return a[i] > b[i] ? 1 : -1;",
  "  return 0;",
  "}",
  "function __cccSemverSatisfies(version, range) {",
  "  const text = String(range).trim();",
  '  if (!text || text === "*") return true;',
  '  if (text.startsWith(">=")) return __cccCompareVersions(version, text.slice(2)) >= 0;',
  '  if (text.startsWith(">")) return __cccCompareVersions(version, text.slice(1)) > 0;',
  '  if (text.startsWith("<=")) return __cccCompareVersions(version, text.slice(2)) <= 0;',
  '  if (text.startsWith("<")) return __cccCompareVersions(version, text.slice(1)) < 0;',
  '  if (text.startsWith("=")) return __cccCompareVersions(version, text.slice(1)) === 0;',
  "  return __cccCompareVersions(version, text) === 0;",
  "}",
  "function __cccWhich(command) {",
  '  const fs = __baseRequire("fs");',
  '  const path = __baseRequire("path");',
  '  const pathEntries = String(process.env.PATH || "").split(path.delimiter).filter(Boolean);',
  '  const extensions = process.platform === "win32" ? String(process.env.PATHEXT || ".EXE;.CMD;.BAT;.COM").split(";") : [""];',
  "  for (const dir of pathEntries) {",
  "    for (const ext of extensions) {",
  '      const candidate = path.join(dir, process.platform === "win32" && path.extname(command) ? command : command + ext);',
  "      try { fs.accessSync(candidate, fs.constants.X_OK); return candidate; } catch {}",
  "    }",
  "  }",
  "  return null;",
  "}",
  "function __cccJsonlParseChunk(chunk) {",
  '  const text = typeof chunk === "string" ? chunk : Buffer.from(chunk).toString("utf8");',
  "  const values = [];",
  "  let read = 0;",
  "  for (const part of text.split(/(?<=\\n)/)) {",
  '    if (!part.endsWith("\\n")) break;',
  "    read += part.length;",
  "    const line = part.trim();",
  "    if (!line) continue;",
  "    try { values.push(JSON.parse(line)); } catch (error) { return { values, read, error, done: false }; }",
  "  }",
  "  return { values, read, done: read >= text.length };",
  "}",
  "// bun file shim (path- or fd-backed); read surface is the commonly used subset.",
  "// _openForWriteSync exists for bun spawn stdio redirection (the ptyHost stderr",
  "// breadcrumb passes a bun file handle as a stdio target); append mode so respawn",
  "// loops do not clobber earlier breadcrumbs. Open errors keep fs error codes so",
  "// callers that inspect error.code (ENOSPC/EACCES/EROFS at the breadcrumb site)",
  "// behave as they would under bun.",
  "// (no literal 'Bun-dot' may appear in preamble text: the preamble is injected",
  "// after the bundle rewrite, and tests assert the wrapped output is Bun-dot-free.)",
  "class __cccBunFile {",
  "  constructor(pathOrFd) {",
  '    if (typeof pathOrFd === "number") { this.fd = pathOrFd; this.name = undefined; }',
  "    else { this.path = String(pathOrFd); this.name = this.path; }",
  "  }",
  '  _target() { return this.fd ?? this.path; }',
  '  _openForWriteSync() { if (this.fd !== undefined) return this.fd; return __baseRequire("fs").openSync(this.path, "a"); }',
  '  async text() { return __baseRequire("fs").readFileSync(this._target(), "utf8"); }',
  "  async json() { return JSON.parse(await this.text()); }",
  '  async bytes() { const buffer = __baseRequire("fs").readFileSync(this._target()); return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength); }',
  "  async arrayBuffer() { const bytes = await this.bytes(); return bytes.slice().buffer; }",
  '  stream() { const fs = __baseRequire("fs"); const { Readable } = __baseRequire("stream"); return Readable.toWeb(this.fd !== undefined ? fs.createReadStream(null, { fd: this.fd, autoClose: false }) : fs.createReadStream(this.path)); }',
  '  async exists() { try { __baseRequire("fs").accessSync(this._target()); return true; } catch { return false; } }',
  '  get size() { try { const fs = __baseRequire("fs"); return (this.fd !== undefined ? fs.fstatSync(this.fd) : fs.statSync(this.path)).size; } catch { return 0; } }',
  '  get lastModified() { try { const fs = __baseRequire("fs"); return (this.fd !== undefined ? fs.fstatSync(this.fd) : fs.statSync(this.path)).mtimeMs; } catch { return 0; } }',
  "}",
  "// bun stdin shim: file-ish view of process.stdin; the bundle consumes it via",
  "// `new Response(stdin.stream()).text()`.",
  "const __cccBunStdin = {",
  '  stream() { return __baseRequire("stream").Readable.toWeb(process.stdin); },',
  "  async text() {",
  "    const chunks = [];",
  "    for await (const chunk of process.stdin) chunks.push(__cccToBuffer(chunk));",
  '    return Buffer.concat(chunks).toString("utf8");',
  "  },",
  "  async json() { return JSON.parse(await this.text()); },",
  "  async bytes() { const chunks = []; for await (const chunk of process.stdin) chunks.push(__cccToBuffer(chunk)); const buffer = Buffer.concat(chunks); return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength); },",
  "};",
  "class __cccTranspiler {",
  "  transformSync(code) {",
  '    const source = typeof code === "string" ? code : String(code);',
  "    let esbuild;",
  '    try { esbuild = __baseRequire("esbuild"); } catch { return source; }',
  '    const options = { loader: "js", target: "esnext", supported: { "top-level-await": false } };',
  "    try {",
  "      return esbuild.transformSync(source, options).code;",
  "    } catch (error) {",
  "      // top-level await is a syntax error in claude's repl (code runs via new vm.Script,",
  "      // not as a module), so wrap it in an async IIFE. a multi-statement wrap resolves to",
  "      // undefined and the repl falls back to resolving the `o` global.",
  '      const isTopLevelAwait = error && Array.isArray(error.errors) && error.errors.some((e) => /top-level await/i.test((e && e.text) || ""));',
  "      if (!isTopLevelAwait) return source;",
  '      const trimmed = source.trim().replace(/;$/, "").trim();',
  '      const startsStatement = /^(?:let|const|var|function|class|return|throw|if|for|while|switch|try|do|import|export|debugger)\\b/.test(trimmed);',
  '      const single = trimmed.length > 0 && !startsStatement && !trimmed.includes("\\n") && !trimmed.includes(";");',
  '      const wrapped = single ? "(async()=>(" + trimmed + "\\n))()" : "(async()=>{" + source + "\\n})()";',
  "      try { return esbuild.transformSync(wrapped, options).code; } catch { return wrapped; }",
  "    }",
  "  }",
  "  transform(code) { return Promise.resolve(this.transformSync(code)); }",
  "  scan() { return { imports: [], exports: [] }; }",
  "  scanImports() { return []; }",
  "}",
  "class __cccTerminal {",
  '  constructor(options = {}) { this.options = options; this.child = null; this.cols = options.cols ?? 80; this.rows = options.rows ?? 24; this.name = options.name ?? "xterm-256color"; this.closed = false; this.rawMode = false; this.pending = []; this.stdin = 0; this.stdout = 1; }',
  "  _attach(child) {",
  '    if (this.closed) throw new Error("bun terminal shim: terminal is closed");',
  "    this.child = child;",
  '    child.stdout?.on("data", (chunk) => this.options.data?.(this, chunk));',
  '    child.stderr?.on("data", (chunk) => this.options.data?.(this, chunk));',
  '    child.stdin?.on("drain", () => this.options.drain?.(this));',
  '    child.once("close", () => { if (this.child === child) this.child = null; });',
  "    while (this.pending.length && child.stdin && !child.stdin.destroyed) child.stdin.write(this.pending.shift());",
  "  }",
  '  write(data) { if (this.closed) return 0; const buffer = __cccToBuffer(data); if (!this.child?.stdin || this.child.stdin.destroyed) { this.pending.push(buffer); return buffer.length; } const ok = this.child.stdin.write(buffer); if (!ok) this.child.stdin.once("drain", () => this.options.drain?.(this)); return buffer.length; }',
  '  resize(cols, rows) { this.cols = cols; this.rows = rows; try { this.child?.kill?.("SIGWINCH"); } catch {} }',
  "  setRawMode(enabled) { this.rawMode = !!enabled; }",
  "  close() { if (this.closed) return; this.closed = true; this.pending = []; try { this.child?.kill(); } catch {} this.options.exit?.(this, 0, null); }",
  "  ref() { this.child?.ref?.(); }",
  "  unref() { this.child?.unref?.(); }",
  "  [Symbol.dispose]() { this.close(); }",
  "  [Symbol.asyncDispose]() { this.close(); return Promise.resolve(); }",
  "}",
  "function __cccSpawnStdio(options) {",
  '  if (options.terminal) return ["pipe", "pipe", "pipe"];',
  "  if (options.stdio) return options.stdio;",
  "  return [",
  '    options.stdin === "pipe" ? "pipe" : options.stdin === "inherit" ? "inherit" : "ignore",',
  '    options.stdout === "inherit" ? "inherit" : options.stdout === "ignore" || options.stdout === null ? "ignore" : "pipe",',
  '    options.stderr === "pipe" ? "pipe" : options.stderr === "ignore" || options.stderr === null ? "ignore" : "inherit",',
  "  ];",
  "}",
  "function __cccResolveSpawnFile(file) {",
  '  const fs = __baseRequire("fs");',
  '  const path = __baseRequire("path");',
  '  if (!file) throw new Error("bun spawn shim: missing command");',
  '  if (path.isAbsolute(file) || file.includes("/") || file.includes("\\\\")) {',
  "    fs.accessSync(file, fs.constants.X_OK);",
  "    return file;",
  "  }",
  "  const resolved = __cccWhich(file);",
  "  if (resolved) return resolved;",
  "  const error = new Error(`bun spawn shim: command not found: ${file}`);",
  '  error.code = "ENOENT";',
  "  throw error;",
  "}",
  "function __cccSpawn(command, options = {}) {",
  '  const childProcess = __baseRequire("child_process");',
  "  const commandArray = Array.isArray(command) ? command : [String(command)];",
  "  const [file, ...args] = commandArray;",
  "  // translate bun-file stdio targets (e.g. stdio:['ignore','ignore',file(logPath)])",
  "  // into fds. node dups fds into the child during spawn(), so the parent copies are",
  "  // closed immediately after; on open/spawn failure they are closed in the catch.",
  "  const openedFds = [];",
  "  const stdio = __cccSpawnStdio(options).map((entry) => {",
  "    if (entry instanceof __cccBunFile) { const fd = entry._openForWriteSync(); if (entry.fd === undefined) openedFds.push(fd); return fd; }",
  "    return entry;",
  "  });",
  "  let child;",
  "  try {",
  "    child = childProcess.spawn(__cccResolveSpawnFile(file), args, { cwd: options.cwd, env: options.env, stdio, detached: options.detached, windowsHide: options.windowsHide, argv0: options.argv0 });",
  "  } finally {",
  '    const fsMod = __baseRequire("fs");',
  "    for (const fd of openedFds) { try { fsMod.closeSync(fd); } catch {} }",
  "  }",
  "  const terminal = options.terminal;",
  "  terminal?._attach?.(child);",
  "  const streamText = (stream) => () => new Promise((resolve, reject) => {",
  '    if (!stream) { resolve(""); return; }',
  "    const chunks = [];",
  '    stream.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));',
  '    stream.once("error", reject);',
  '    stream.once("end", () => resolve(Buffer.concat(chunks).toString("utf8")));',
  "  });",
  "  let exitCode = null;",
  "  let signalCode = null;",
  "  const exited = new Promise((resolve, reject) => {",
  '    child.once("error", (error) => { options.onExit?.(result, null, null, error); reject(error); });',
  '    child.once("exit", (code, signal) => { exitCode = code; signalCode = signal; options.onExit?.(result, code, signal); resolve(code ?? (signal ? 1 : 0)); });',
  "  });",
  "  const result = {",
  "    pid: child.pid ?? 0,",
  "    stdin: terminal ? null : child.stdin,",
  "    stdout: terminal ? null : { text: streamText(child.stdout) },",
  "    stderr: terminal ? null : { text: streamText(child.stderr) },",
  "    readable: terminal ? null : { text: streamText(child.stdout) },",
  "    terminal,",
  "    exited,",
  "    get exitCode() { return exitCode; },",
  "    get signalCode() { return signalCode; },",
  "    get killed() { return child.killed; },",
  "    kill: (signal) => child.kill(signal),",
  "    ref: () => child.ref(),",
  "    unref: () => child.unref(),",
  "    send: (message) => child.send?.(message),",
  "    disconnect: () => child.disconnect?.(),",
  "    resourceUsage: () => child.resourceUsage?.(),",
  "    [Symbol.dispose]() { child.kill(); },",
  "    [Symbol.asyncDispose]() { child.kill(); return Promise.resolve(); },",
  "  };",
  "  return result;",
  "}",
  "function __cccListenPort(port) {",
  "  const value = Number(port ?? 0);",
  "  if (value > 0) return value;",
  "  return 49152 + Math.floor(Math.random() * 16384);",
  "}",
  "function __cccListen(options) {",
  '  const net = __baseRequire("net");',
  "  const sockets = new Set();",
  "  const listenPort = __cccListenPort(options.port);",
  "  const server = net.createServer((socket) => {",
  "    sockets.add(socket);",
  "    socket.data = {};",
  "    const bunSocket = {",
  "      get data() { return socket.data; },",
  "      set data(value) { socket.data = value; },",
  "      write: (data) => { if (socket.destroyed || socket.writableEnded || socket.writableNeedDrain) return 0; const buffer = __cccToBuffer(data); socket.write(buffer); return buffer.length; },",
  "      end: () => socket.end(),",
  "    };",
  "    let closeError = null;",
  "    options.socket?.open?.(bunSocket);",
  '    socket.on("data", (data) => options.socket?.data?.(bunSocket, data));',
  '    socket.on("drain", () => options.socket?.drain?.(bunSocket));',
  '    socket.on("close", () => { sockets.delete(socket); options.socket?.close?.(bunSocket, closeError); });',
  '    socket.on("error", (error) => { closeError = error; options.socket?.error?.(bunSocket, error); });',
  "  });",
  "  if (options.unix || options.path) server.listen(options.unix ?? options.path);",
  '  else server.listen(listenPort, options.hostname ?? "127.0.0.1");',
  "  const address = server.address();",
  "  return {",
  '    get port() { const current = server.address(); return typeof current === "object" && current ? current.port : (typeof address === "object" && address ? address.port : listenPort); },',
  "    stop(force) { for (const socket of sockets) force ? socket.destroy() : socket.end(); server.close(); },",
  "    ref() { server.ref(); },",
  "    unref() { server.unref(); },",
  "  };",
  "}",
  "// NOTE: WebView is deliberately NOT shimmed. The bundle guards it with",
  '// `typeof Bun<"u"&&"WebView"in Bun` before calling WebView.closeAll(); absence is',
  "// the correct answer (no native webview under node) and a stub would get called.",
  "const __cccBun = {",
  '  YAML: __require("yaml"),',
  "  JSONL: { parseChunk: __cccJsonlParseChunk },",
  "  embeddedFiles: [],",
  '  version: "0.0.0-ccc-node-shim",',
  "  isStandaloneExecutable: false,",
  "  semver: { order: __cccCompareVersions, satisfies: __cccSemverSatisfies },",
  "  which: __cccWhich,",
  "  stringWidth: __cccStringWidth,",
  "  hash: __cccBunHash,",
  "  wrapAnsi: __cccWrapAnsi,",
  "  stripANSI: __cccStripAnsi,",
  "  Transpiler: __cccTranspiler,",
  '  generateHeapSnapshot: () => Buffer.from(""),',
  "  gc: () => {},",
  "  spawn: __cccSpawn,",
  "  Terminal: __cccTerminal,",
  "  listen: __cccListen,",
  "  file: (pathOrFd) => new __cccBunFile(pathOrFd),",
  "  stdin: __cccBunStdin,",
  '  deepEquals: (a, b) => __baseRequire("util").isDeepStrictEqual(a, b),',
  "  // claude gateway features require the native bun binary; the bundle's own",
  '  // `typeof Bun>"u"` branch says as much. Clear errors beat "not a function".',
  '  serve: () => { throw new Error("ccc bun shim: serve() is not supported (claude gateway requires the native bun binary)"); },',
  '  SQL: class { constructor() { throw new Error("ccc bun shim: SQL is not supported (claude gateway requires the native bun binary)"); } },',
  "};",
  "globalThis.__cccBun ??= __cccBun;",
  "globalThis.Bun ??= globalThis.__cccBun;",
  "var Bun = globalThis.Bun;",
  'const __module = typeof module !== "undefined" ? module : { exports: {} };',
  "const __exports = __module.exports;",
  "",
].join("\n");

const ENTRY_INVOCATION = "\n__bun_entry(__exports, __require, __module, __filename__, __dirname__);\n";

// Bun.Transpiler fallback for the `typeof Bun === "undefined"` branch only — dead
// under CCC since the PREAMBLE always defines Bun. The live REPL transpiler is
// `__cccTranspiler` above; keep top-level-await handling in sync across both.
const TRANSPILER_BAIL = 'if(typeof Bun>"u")throw Error("unreachable: Bun required")';
const TRANSPILER_POLYFILL = [
  'if(typeof Bun>"u")return ui$??=(()=>{',
  'const __esb=require("esbuild");',
  "const __tx=(c)=>{",
  'if(typeof c!=="string"||!c)return c;',
  "try{",
  '__esb.transformSync(c,{loader:"js",target:"esnext",supported:{"top-level-await":false}});',
  "return c;",
  "}catch(e){",
  'const tla=e&&e.errors&&e.errors.some((er)=>/top-level await/i.test(er.text||""));',
  "if(!tla)return c;",
  'const t=c.trim().replace(/;$/,"").trim();',
  'const single=(t.indexOf("\\n")<0&&t.indexOf(";")<0&&t.length>0);',
  'return single?"(async()=>("+t+"\\n))()":"(async()=>{"+c+"\\n})()";',
  "}",
  "};",
  "return{transformSync:__tx,transform:(c)=>Promise.resolve(__tx(c)),scan:()=>({imports:[],exports:[]})};",
  "})()",
].join("");

const BUN_STRING_WIDTH_RE = /function ([\w$]+)\(([\w$]+)\){return Bun\.stringWidth\(\2,[\w$]+\)}/;
const buildStringWidthReplacement = (fn: string, value: string) =>
  `function ${fn}(${value}){return __cccStringWidth(${value})}`;

const BUN_DOT_RE = /\bBun\./g;
const GLOBAL_THIS_BUN_RE = /\bglobalThis\.Bun\b/g;

export const PREAMBLE_VERSION = createHash("sha256")
  .update(PREAMBLE)
  .update(ENTRY_INVOCATION)
  .update(TRANSPILER_BAIL)
  .update(TRANSPILER_POLYFILL)
  .update(String(BUN_STRING_WIDTH_RE))
  .update(buildStringWidthReplacement("$", "_"))
  .update(String(BUN_DOT_RE))
  .update(String(GLOBAL_THIS_BUN_RE))
  .digest("hex")
  .slice(0, 16);

export const wrapForNode = (raw: Buffer) => {
  let src = raw.toString("utf8");

  if (src.includes(TRANSPILER_BAIL)) {
    src = src.replace(TRANSPILER_BAIL, TRANSPILER_POLYFILL);
  }
  src = src.replace(BUN_STRING_WIDTH_RE, (_match, fn, value) => buildStringWidthReplacement(fn, value));
  src = src.replace(BUN_DOT_RE, "__cccBun.");
  src = src.replace(GLOBAL_THIS_BUN_RE, "globalThis.__cccBun");

  const entryIdx = src.indexOf(NATIVE_BUN_ENTRY_MARKER);
  if (entryIdx === -1) {
    throw new Error(
      `native-preamble: bun entry wrapper '${NATIVE_BUN_ENTRY_MARKER}' not found in extracted bundle. ` +
        "The bundle wrapping shape changed. Update NATIVE_BUN_ENTRY_MARKER in src/native/constants.ts.",
    );
  }

  const firstNl = src.indexOf("\n");
  const insertAt = firstNl === -1 ? 0 : firstNl + 1;

  const withNamedEntry = `${src.slice(0, entryIdx)}const __bun_entry = ${src.slice(entryIdx)}`;
  const withPreamble = withNamedEntry.slice(0, insertAt) + PREAMBLE + withNamedEntry.slice(insertAt);

  return withPreamble + ENTRY_INVOCATION;
};
